[package]
name = "staking-bank-module"
version = "0.0.0"
authors = [ "you",]
edition = "2021"

[lib]
path = "src/staking_bank_module.rs"


[dependencies.multiversx-sc]
version = "=0.41.3"
features = ["esdt-token-payment-legacy-decode"]
